### ISSUE TITLE
After changing the git repo to Github.io and doing a hard git reset and pull, I can launch Sickrage. 

### ISSUE THREAD

**Issue by abetancort** [SickRage/sickrage.github.io#249]
I don’t find any obvious python file to launch... since I don’t have access to the previous resources in the Sickrage repo, I don´t know if it’s that this temporary repo is not a complete fork and there are files missing... if you let me know I can recover the missing files from yesterday’s incremental backup of the system files and wait until the DMCA issue is sorted .

Thanks in advance.

Alfonso

**Comment by sharkykh** [comment]
You can find a python file to launch because this is simply the repo for the site: [sickrage.github.io](http://sickrage.github.io)

This **is** temporary.
> #### 2017-07-20
> A false DMCA takedown request was sent to GitHub, resulting in multiple repositories, including 
SickRage/SickRage, to be taken down. We're countering this and should have the repo back very soon. We thank you for your patience.

There's nothing I can do until the takedown is lifted.
But do keep your backups.

We'll update everyone when we're back online.

**Comment by GodZZila** [comment]
Sharkykh,

Have you an expectation when it will be online again? Normally it woudl't take 8 days to lift up the takedown.

With Kind Regards,

GodZZila

**Comment by sharkykh** [comment]
@GodZZila 
I'm not the owner, but as far as I know, the takedown is expected to be lifted this week (between Sunday and Wednesday).

Github forces us to wait 10 to 14 days after filing the counter notice.

**Comment by miigotu** [comment]
https://github.com/SickRage/sickrage.github.io/commit/b9dbc0f55c9975bc81ed5f5f2a1021777d519d22#commitcomment-23385782
